use exitfailure::ExitFailure;

fn main() -> Result<(), ExitFailure>{
    println!("Issue parser integration ... ");
    
    Ok(())
}
